services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'flask-crud'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - type: bind
        source: C:\DESKTOP\rocketseat\mysql\var\lib/mysql
        target: /var/lib/mysql
        read_only: false
   
    
